# Generated by Django 3.2.3 on 2021-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(null=True)),
                ('orderedItemID', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('gender', models.TextField(null=True)),
            ],
        ),
    ]
