# Generated by Django 3.2.3 on 2021-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210526_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orderedItemID',
            field=models.IntegerField(),
        ),
    ]
